stages:
  - Test
  - Release
  - Build
  - Push

build-v2:
  stage: Build
  only:
    - tags
  tags:
    - devMini
  script:
    - cp /Users/devmini/codecapi/capiportal/.env desktop/.erb/configs
    - cd desktop
    - nvm use 16
    - yarn install --frozen-lockfile
    - yarn package
