# variables:
#   CONTAINER_IMAGE: registry.gitlab.com/codecapi/codecapi-portale/portal-backend

# stages:
#   - Test
#   - Release
#   - Build
#   - Push

# release:
#   stage: Release
#   image: node:14
#   only:
#     - master
#   before_script:
#     - npm install -g semantic-release @semantic-release/gitlab @semantic-release/commit-analyzer @semantic-release/release-notes-generator
#   script:
#     - semantic-release

# build-tags:
#   stage: Build
#   only:
#     - tags
#   image: docker:stable
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - docker pull $CONTAINER_IMAGE:latest-build || true
#     - docker build --cache-from $CONTAINER_IMAGE:latest-build --tag $CONTAINER_IMAGE:latest-build --target build .
#     - docker push $CONTAINER_IMAGE:latest-build
#     - docker build --cache-from $CONTAINER_IMAGE:latest-build --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_TAG .
#     - docker push $CONTAINER_IMAGE:latest
#     - docker push $CONTAINER_IMAGE:$CI_COMMIT_TAG

# build-mr:
#   stage: Build
#   # only:
#   #   - merge_requests
#   image: docker:stable
#   services:
#     - docker:dind
#   script:
#     - docker pull $CONTAINER_IMAGE:latest || true
#     - docker build --cache-from $CONTAINER_IMAGE:latest .
